apiVersion: docdb.aws.upbound.io/v1beta1
kind: EventSubscription
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1beta1/eventsubscription
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    enabled: true
    eventCategories:
    - creation
    - failure
    region: us-east-2
    snsTopicArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sourceType: db-cluster
---
apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: docdb/v1beta1/eventsubscription
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2

---
