apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: KinesisStreamingDestination
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/kinesisstreamingdestination
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    streamArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tableNameSelector:
      matchLabels:
        testing.upbound.io/example-name: mytable

---

apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/table
  labels:
    testing.upbound.io/example-name: mytable
  name: mytable
spec:
  forProvider:
    attribute:
    - name: exampleHashKey
      type: S
    hashKey: exampleHashKey
    region: us-east-2
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
    billingMode: PAY_PER_REQUEST

---

apiVersion: kinesis.aws.kubeform.com/v1alpha1
kind: Stream
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/kinesisstreamingdestination
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    shardCount: 1

---
