
apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: TableReplica
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/tablereplica
  labels:
    testing.upbound.io/example-name: example
  name: tablereplica
spec:
  forProvider:
    globalTableArn: arn:aws:dynamodb:us-east-2:452618475015:table/mytable
    region: us-west-2

---

apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/table
  labels:
    testing.upbound.io/example-name: mytable
  name: mytable
spec:
  forProvider:
    attribute:
    - name: exampleHashKey
      type: S
    hashKey: exampleHashKey
    region: us-east-2
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
    billingMode: PAY_PER_REQUEST

---