apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capi-cluster-presets
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: capi-cluster-presets
  targetNamespace: capi-cluster
  storageNamespace: capi-cluster
  chart:
    spec:
      chart: capi-cluster-presets
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
