apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-creds
  namespace: demo
stringData:
  password: <password>
  username: <username>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unsealer-creds
  namespace: demo
stringData:
  access_key: <access_key>
  secret_key: <secret_key>
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    etcd:
      address: <etcd-server-address>
      credentialSecretName: vault-backend-creds
  replicas: 1
  unsealer:
    mode:
      awsKmsSsm:
        credentialSecret: vault-unsealer-creds
        kmsKeyID: <kms-key-id>
        region: <region>
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
