apiVersion: kubedb.com/v1
kind: Kafka
metadata:
  name: kafka-quickstart
  namespace: demo
spec:
  version: 3.4.0
  replicas: 3
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  deletionPolicy: DoNotTerminate