apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../base
kind: Kustomization
patchesJson6902:
- path: patch.yaml
  target:
    group: kubedb.com
    kind: MongoDB
    name: mongodb
    namespace: demo
    version: v1alpha2
resources:
- mongodb-configserver-config.yaml
- mongodb-mongos-config.yaml
- mongodb-shard-config.yaml
