apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure
spec:
  #package: xpkg.kubedb.com/upbound/provider-azure:v0.20.0
  package: xpkg.kubedb.com/upbound/provider-azure:v0.38.2


