apiVersion: v1
kind: Secret
metadata:
  name: documentdb-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: kubedb.com/v1alpha2
kind: DocumentDB
metadata:
  name: documentdb
  namespace: default
spec:
  version: "24.4.1"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  podTemplate:
    spec:
      containers:
        - name: documentdb
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
      podPlacementPolicy:
        name: default
      nodeSelector:
        app: documentdbs.kubedb.com
        instance: hello
        namespace: default
        nodepool: standard-bsv2-family
      tolerations:
        - key: app
          operator: "Equal"
          value: "documentdbs.kubedb.com"
          effect: "NoSchedule"
        - key: instance
          operator: "Equal"
          value: hello
          effect: "NoSchedule"
        - key: namespace
          operator: "Equal"
          value: default
          effect: "NoSchedule"
        - key: nodepool
          operator: "Equal"
          value: standard-bsv2-family
          effect: "NoSchedule"
  deletionPolicy: WipeOut
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: DocumentDBAutoscaler
metadata:
  name: documentdb
  namespace: demo
spec:
  databaseRef:
    name: documentdb
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    documentdb:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
