- op: add
  path: /spec/configSecret
  value:
    name: mongodb-config
- op: add
  path: /spec/shardTopology
  value:
    configServer:
      configSecret:
        name: mongodb-configserver-config
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      configSecret:
        name: mongodb-mongos-config
      replicas: 2
    shard:
      configSecret:
        name: mongodb-shard-config
      replicas: 3
      shards: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
- op: remove
  path: /spec/storage
