apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cluster-auth-manager
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: cluster-auth-manager
  targetNamespace: open-cluster-management-addon
  storageNamespace: open-cluster-management-addon
  chart:
    spec:
      chart: cluster-auth-manager
      version: "v2024.2.25"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  dependsOn:
    - name: cluster-manager-hub
    - name: managed-serviceaccount-manager
    - name: cluster-gateway-manager
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
