apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxcd-addon-manager
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: fluxcd-addon-manager
  targetNamespace: open-cluster-management
  storageNamespace: open-cluster-management
  chart:
    spec:
      chart: fluxcd-addon-manager
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  dependsOn:
    - name: cluster-manager-hub
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
