apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: managed-serviceaccount-manager
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: managed-serviceaccount-manager
  targetNamespace: open-cluster-management-addon
  storageNamespace: open-cluster-management-addon
  chart:
    spec:
      chart: managed-serviceaccount-manager
      version: "v2024.2.25"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
