apiVersion: spanner.gcp.kubedb.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.kubedb.com/example-id: spanner/v1alpha1/instance
  labels:
    testing.kubedb.com/example-name: example2
  name: example2
spec:
  forProvider:
    config: regional-us-central1
    displayName: Test Spanner Instance
    labels:
      foo: bar
    numNodes: 2