apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: mongodb
  namespace: demo
spec:
  eksNodegroupName: nodegroup
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: mongodb
  namespace: demo
spec:
  clusterName: cluster-x
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: cluster-x
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: mongodb
---
apiVersion: external-dns.appscode.com/v1alpha1
kind: ExternalDNS
metadata:
  name: mongodb
  namespace: demo
spec:
  source:
    type:
      group: ""
      version: v1
      kind: Node
    node:
      labelFilter: eks.amazonaws.com/nodegroup=nodegroup
  provider: aws
  aws:
    zoneType: public
