apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capa-vpc-peering-operator
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: capa-vpc-peering-operator
  targetNamespace: crossplane-system
  storageNamespace: crossplane-system
  chart:
    spec:
      chart: capa-vpc-peering-operator
      version: "v2023.03.23"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
