apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: postgres
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  namespace: demo
stringData:
  user.conf: |
    max_connections=110
    shared_buffers=258MB
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgres-ca
  namespace: demo
spec:
  ca:
    secretName: postgres-ca
---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres
  namespace: demo
spec:
  authSecret:
    name: postgres-auth
  clientAuthMode: scram
  configSecret:
    name: postgres-config
  init:
    waitForInitialRestore: true
  leaderElection:
    electionTick: 10
    heartbeatTick: 1
    maximumLagBeforeFailover: 33554432
    period: 100ms
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  podTemplate:
    spec:
      containerSecurityContext:
        privileged: false
        runAsGroup: 1000620000
        runAsUser: 1000620000
  sslMode: verify-full
  standbyMode: Hot
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: postgres-ca
  version: 13.2-debian
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
    release: prometheus-stack
  name: postgres
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/name: postgreses.kubedb.com
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-init-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/postgres
    storageSecretName: gcs-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-init-repo-cred
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: postgres
type: Opaque
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/postgres
    storageSecretName: gcs-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-repo-cred
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: postgres
type: Opaque
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres
  namespace: demo
spec:
  repository:
    name: postgres-init-repo
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/2 * * * *'
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: postgres
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-init
  namespace: demo
spec:
  repository:
    name: postgres-init-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: postgres
---
apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: postgres-storage
  namespace: demo
spec:
  storage:
    provider: gcs
    gcs:
      bucket: kubedb-testing
      prefix: /postgres
      secret: postgres-storage-cred
  deletionPolicy: Delete
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-storage-cred
  namespace: demo
stringData:
  password: ""
  username: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-encryption-secret
  namespace: demo
stringData:
  key: ""
---
apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: postgres
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Postgres
    name: postgres
    namespace: demo
  backends:
    - name: postgres-backend
      storageRef:
        name: postgres-storage
        namespace: demo
      retentionPolicy:
        name: postgres-retention-policy
        namespace: demo
  sessions:
    - name: postgres-frequent-backup
      sessionHistoryLimit: 2
      scheduler:
        schedule: "*/5 * * * *"
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: postgres-repo
          backend: postgres-backend
          directory: /postgres-repo
          encryptionSecret:
            name: postgres-encryption-secret
            namespace: demo
      addon:
        name: postgres-addon
        tasks:
          - name: logical-backup
        jobTemplate:
          spec:
            securityContext:
              runAsUser: 0
              runAsGroup: 0
---
apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: postgres-retention-policy
  namespace: demo
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 5
  failedSnapshots:
    last: 2
---
apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: postgres
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Postgres
    name: postgres
    namespace: demo
  dataSource:
    snapshot: latest
    repository: postgres-repo
    encryptionSecret:
      name: postgres-encryption-secret
      namespace: demo
  addon:
    name: postgres-addon
    tasks:
      - name: logical-backup-restore
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
