apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: mysql-init-repo
  namespace: demo
  labels:
    app.kubernetes.io/name: mysqls.kubedb.com
    app.kubernetes.io/instance: mysql
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/mysql/mysql
    storageSecretName: gcs-secret
