apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: mysql-init
  namespace: demo
  labels:
    app.kubernetes.io/name: mysqls.kubedb.com
    app.kubernetes.io/instance: mysql
spec:
  task:
    name: mysql-restore-8.0.21
  repository:
    name: mysql-init-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mysql
  rules:
    - snapshots: [latest]
