apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vcluster
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: vcluster
  targetNamespace: open-cluster-management
  storageNamespace: open-cluster-management
  chart:
    spec:
      chart: vcluster
      version: "0.16.4"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
