apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-std
  namespace: demo
spec:
  version: "4.2.3"
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  terminationPolicy: WipeOut
  authSecret:
    name: custom-auth
