apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-secrets-store-provider-azure
  namespace: kubeops
  labels:
    app.kubernetes.io/component: csi-secrets-store-provider-azure
spec:
  interval: 5m
  timeout: 30m
  releaseName: csi-secrets-store-provider-azure
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      version: "1.0.50"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
