apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver-provider-gcp
  namespace: kubeops
  labels:
    app.kubernetes.io/component: secrets-store-csi-driver-provider-gcp
spec:
  interval: 5m
  timeout: 30m
  releaseName: secrets-store-csi-driver-provider-gcp
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: secrets-store-csi-driver-provider-gcp
      version: "1.0.50"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
