apiVersion: v1
kind: Secret
metadata:
  name: druid-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: druid-config
  namespace: demo
stringData:
  druid.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: druid-ca
  namespace: demo
spec:
  ca:
    secretName: druid-ca
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: druid
    app.kubernetes.io/name: druids.kubedb.com
    release: prometheus-stack
  name: druid
  namespace: demo
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: druid
      app.kubernetes.io/name: druids.kubedb.com
---
apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid
  namespace: druid
spec:
  version: 28.0.1
  storageType: Ephemeral
  #  configSecret:
  #    name: custom-config
  deepStorage:
    type: s3
    configSecret:
      name: deep-storage-config
  metadataStorage:
    name: mysql-cluster
    namespace: druid
    createTables: true
  zookeeperRef:
    name: zk-cluster
    namespace: druid
  topology:
    coordinators:
      replicas: 1
    overlords:
      replicas: 1
    brokers:
      podTemplate:
        spec:
          nodeSelector:
            app: kubedb
            instance: druid
            component: druid-database
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: kubedb
            - effect: NoSchedule
              key: instance
              operator: Equal
              value: druid
            - effect: NoSchedule
              key: component
              operator: Equal
              value: druid-database
            - effect: NoSchedule
              key: nodepool_type
              operator: Equal
              value: n2-standard-2
          containers:
            - name: druid
              resources:
                requests:
                  cpu: 700m
                  memory: "1200Mi"
      replicas: 1
    historicals:
      replicas: 1
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
#        storageClassName: standard
    middleManagers:
      replicas: 1
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
#        storageClassName: standard
    routers:
      replicas: 1
  serviceTemplates:
  - alias: primary
    spec:
      type: LoadBalancer
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: DruidAutoscaler
metadata:
  name: druid
  namespace: demo
spec:
  databaseRef:
    name: repl
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    node:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
---
apiVersion: catalog.appscode.com/v1alpha1
kind: DruidBinding
metadata:
  name: druid
  namespace: demo
spec:
  sourceRef:
    name: druid
    namespace: demo
