apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubedb-ui-presets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kubedb-ui-presets
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubedb-ui-presets
  targetNamespace: kubedb
  storageNamespace: kubedb
  chart:
    spec:
      chart: kubedb-ui-presets
      version: "v2024.6.18"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    deployment:
      default: Shared
      toggle: true
    clusterTier:
      default: "GeneralPurpose"
      toggle: true
      nodeTopology:
        available: []
        default: ""
        toggle: true
      placement:
        available: []
        default: ""
        toggle: true
    databases:
      Cassandra:
        versions:
          available: [ "4.1.8", "5.0.3" ]
          default: "5.0.3"
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      ClickHouse:
        versions:
          available: [ "24.4.1" ]
          default: "24.4.1"
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      Druid:
        versions:
          available: [ "28.0.1", "30.0.1", "31.0.0" ]
          default: "31.0.0"
          toggle: true
        mode:
          available: ["Topology"]
          default: "Topology"
          toggle: true
      Elasticsearch:
        versions:
          available: [ "xpack-8.17.2", "xpack-7.17.27", "opensearch-1.3.13", "opensearch-2.19.0" ]
          default: "xpack-8.17.2"
          toggle: true
        mode:
          available: [ "Combined", "Topology" ]
          default: "Topology"
          toggle: true
      FerretDB:
        versions:
          available: [ "1.18.0", "1.23.0", "2.0.0" ]
          default: "2.0.0"
          toggle: true
        mode:
          available: [ "PrimaryOnly", "PrimaryAndSecondary" ]
          default: "PrimaryAndSecondary"
          toggle: true
      Kafka:
        versions:
          available: [ "3.7.2", "3.8.1", "3.9.0" ]
          default: "3.9.0"
          toggle: true
        mode:
          available: [ "Combined", "Topology" ]
          default: "Topology"
          toggle: true
      Ignite:
        versions:
          available: [ "2.17.0" ]
          default: "2.17.0"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      MariaDB:
        versions:
          available: [ "10.5.23", "10.6.16", "11.5.2" ]
          default: "11.5.2"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Memcached:
        versions:
          available: [ "1.5.22", "1.6.29", "1.6.33" ]
          default: "1.6.33"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      MongoDB:
        versions:
          available: ["4.4.26", "percona-5.0.23", "6.0.12", "7.0.16", "8.0.4"]
          default: "7.0.16"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset", "Sharded" ]
          default: "Replicaset"
          toggle: true
      MSSQLServer:
        versions:
          available: [ "2022-cu12", "2022-cu14", "2022-cu16" ]
          default: "2022-cu16"
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      MySQL:
        versions:
          available: ["5.7.44", "8.0.36", "8.4.2"]
          default: "8.4.2"
          toggle: true
        mode:
          available: [ "Standalone", "GroupReplication", "InnoDBCluster", "RemoteReplica", "SemiSync" ]
          default: "GroupReplication"
          toggle: true
      PerconaXtraDB:
        versions:
          available: [ "8.0.26", "8.0.40", "8.4.3" ]
          default: "8.4.3"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      PgBouncer:
        versions:
          available: [ "1.17.0", "1.18.0", "1.23.1", "1.24.0" ]
          default: "1.24.0"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Pgpool:
        versions:
          available: [ "4.4.5", "4.5.0", "4.5.3" ]
          default: "4.5.3"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Postgres:
        versions:
          available: [ "13.20", "14.17", "15.12", "16.8", "17.4" ]
          default: "17.4"
          toggle: true
        mode:
          available: [ "Standalone", "Cluster", "RemoteReplica" ]
          default: "Cluster"
          toggle: true
      ProxySQL:
        versions:
          available: [ "2.3.2-debian", "2.4.4-debian", "2.6.3-debian" ]
          default: "2.6.3-debian"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      RabbitMQ:
        versions:
          available: [ "3.12.12", "3.13.2", "4.0.4" ]
          default: "4.0.4"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Redis:
        versions:
          available: [ "6.2.14", "7.2.4", "7.4.1", "valkey-8.1.1" ]
          default: "valkey-8.1.1"
          toggle: true
        mode:
          available: [ "Standalone", "Cluster", "Sentinel" ]
          default: "Cluster"
          toggle: true
      Singlestore:
        versions:
          available: ["8.1.32", "8.5.30", "8.7.10"]
          default: "8.7.10"
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      Solr:
        versions:
          available: [ "8.11.2", "9.6.1", "9.8.0" ]
          default: "9.8.0"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset", "Topology" ]
          default: "Replicaset"
          toggle: true
      ZooKeeper:
        versions:
          available: [ "3.7.2", "3.8.3", "3.9.1" ]
          default: "3.9.1"
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
    storageClasses:
      available: []
      default: ""
      toggle: true
    tls:
      default: false
      toggle: true
    clusterIssuers:
      available: []
      default: ""
      toggle: true
    expose:
      default: false
      toggle: true
    showPreview: false
    monitoring:
      # Name of monitoring agent (one of "prometheus.io", "prometheus.io/operator", "prometheus.io/builtin")
      agent: prometheus.io/operator
      exporter:
        resources: # +doc-gen:break
          requests:
            cpu: 100m
            memory: 128Mi
      toggle: true
    alert:
      toggle: true
    authCredential:
      customize: true
      referExisting: true
    customConfiguration: true
    deletionPolicy:
      default: WipeOut
      toggle: true
    backup:
      enable:
        default: true
        toggle: true
      by: BackupConfiguration
    archiver:
      enable:
        toggle: true
        default: false
    pointInTimeRecovery:
      default: false
      toggle: true
    leftPanel:
      showInsights: true
      showVaultInfo: true
      showOperations: true
      showBackup: true
      showBackupLegacy: false
      showSecurity: false
