apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb-provider-azure
  namespace: kubeops
  labels:
    ace.appscode.com/feature: kubedb-provider-azure
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubedb-provider-azure
  targetNamespace: crossplane-system
  storageNamespace: crossplane-system
  chart:
    spec:
      chart: kubedb-provider-azure
      version: "v2023.12.11"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
