apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubedb-ui-presets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kubedb-ui-presets
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubedb-ui-presets
  targetNamespace: kubedb
  storageNamespace: kubedb
  chart:
    spec:
      chart: kubedb-ui-presets
      version: "v2024.6.18"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    deployment:
      default: Shared
      toggle: true
    clusterTier:
      default: "GeneralPurpose"
      toggle: true
      nodeTopology:
        available: []
        default: ""
        toggle: true
      placement:
        available: []
        default: ""
        toggle: true
    databases:
      Cassandra:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      ClickHouse:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      Druid:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: ["Topology"]
          default: "Topology"
          toggle: true
      Elasticsearch:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Combined", "Topology" ]
          default: "Topology"
          toggle: true
      FerretDB:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "PrimaryOnly", "PrimaryAndSecondary" ]
          default: "PrimaryAndSecondary"
          toggle: true
      Hazelcast:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Combined", "Topology" ]
          default: "Topology"
          toggle: true
      Kafka:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Combined", "Topology" ]
          default: "Topology"
          toggle: true
      Ignite:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      MariaDB:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Memcached:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      MongoDB:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset", "Sharded" ]
          default: "Replicaset"
          toggle: true
      MSSQLServer:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      MySQL:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "GroupReplication", "InnoDBCluster", "RemoteReplica", "SemiSync" ]
          default: "GroupReplication"
          toggle: true
      Oracle:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "DataGuard" ]
          default: "DataGuard"
          toggle: true
      PerconaXtraDB:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      PgBouncer:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Pgpool:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Postgres:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Cluster", "RemoteReplica" ]
          default: "Cluster"
          toggle: true
      ProxySQL:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      RabbitMQ:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
      Redis:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Cluster", "Sentinel" ]
          default: "Cluster"
          toggle: true
      Singlestore:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Topology" ]
          default: "Topology"
          toggle: true
      Solr:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset", "Topology" ]
          default: "Replicaset"
          toggle: true
      ZooKeeper:
        versions:
          available: []
          default: ""
          toggle: true
        mode:
          available: [ "Standalone", "Replicaset" ]
          default: "Replicaset"
          toggle: true
    storageClasses:
      available: []
      default: ""
      toggle: true
    tls:
      default: false
      toggle: true
    clusterIssuers:
      available: []
      default: ""
      toggle: true
    expose:
      default: false
      toggle: true
    showPreview: false
    monitoring:
      # Name of monitoring agent (one of "prometheus.io", "prometheus.io/operator", "prometheus.io/builtin")
      agent: prometheus.io/operator
      exporter:
        resources: # +doc-gen:break
          requests:
            cpu: 100m
            memory: 128Mi
      toggle: true
    alert:
      toggle: true
    authCredential:
      customize: true
      referExisting: true
    customConfiguration: true
    deletionPolicy:
      default: WipeOut
      toggle: true
    backup:
      enable:
        default: true
        toggle: true
      by: BackupConfiguration
    archiver:
      enable:
        toggle: true
        default: false
    pointInTimeRecovery:
      default: false
      toggle: true
    leftPanel:
      showInsights: true
      showVaultInfo: true
      showOperations: true
      showBackup: true
      showBackupLegacy: false
      showSecurity: false
