apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb-opscenter
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubedb-opscenter
  targetNamespace: kubedb
  storageNamespace: kubedb
  chart:
    spec:
      chart: kubedb-opscenter
      version: "v2023.02.28"
      sourceRef:
        kind: HelmRepository
        name: kubedb
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
