apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubedb-ui-presets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kubedb-ui-presets
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubedb-ui-presets
  targetNamespace: kubedb
  storageNamespace: kubedb
  chart:
    spec:
      chart: kubedb-ui-presets
      version: "v2024.6.18"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    deployment:
      default: Shared
      toggle: true
    clusterTier:
      default: "GeneralPurpose"
      toggle: true
      nodeTopology:
        available: []
        default: ""
        toggle: true
      placement:
        available: []
        default: ""
        toggle: true
    databases:
      ClickHouse:
        versions:
          available: [ "24.4.1" ]
          default: "24.4.1"
          toggle: true
      Druid:
        versions:
          available: [ "28.0.1", "30.0.0" ]
          default: "30.0.0"
          toggle: true
      Elasticsearch:
        versions:
          available: [ "xpack-8.14.1", "xpack-7.17.15", "opensearch-1.3.13", "opensearch-2.14.0" ]
          default: "xpack-8.14.1"
          toggle: true
      FerretDB:
        versions:
          available: [ "1.18.0", "1.23.0"]
          default: "1.23.0"
          toggle: true
      Kafka:
        versions:
          available: [ "3.4.1", "3.5.2", "3.6.1" ]
          default: "3.5.2"
          toggle: true
      MariaDB:
        versions:
          available: [ "10.5.23", "10.6.16", "11.2.2" ]
          default: "10.6.16"
          toggle: true
      Memcached:
        versions:
          available: [ "1.5.22", "1.6.22" ]
          default: "1.6.22"
          toggle: true
      MongoDB:
        versions:
          available: ["4.4.26", "5.0.26", "6.0.12"]
          default: "6.0.12"
          toggle: true
      MSSQLServer:
        versions:
          available: [ "2022-cu12" ]
          default: "2022-cu12"
          toggle: true
      MySQL:
        versions:
          available: ["5.7.44", "8.0.36", "8.2.0"]
          default: "8.0.36"
          toggle: true
      PerconaXtraDB:
        versions:
          available: [ "8.0.26", "8.0.28", "8.0.31" ]
          default: "8.0.31"
          toggle: true
      PgBouncer:
        versions:
          available: [ "1.17.0", "1.18.0", "1.23.1" ]
          default: "1.23.1"
          toggle: true
      Pgpool:
        versions:
          available: [ "4.4.5", "4.5.0","4.5.3" ]
          default: "4.5.0"
          toggle: true
      Postgres:
        versions:
          available: [ "13.13", "14.10", "15.5", "16.1" ]
          default: "15.5"
          toggle: true
      ProxySQL:
        versions:
          available: [ "2.3.2-debian", "2.4.4-debian" ]
          default: "2.3.2-debian"
          toggle: true
      RabbitMQ:
        versions:
          available: [ "3.12.12", "3.13.2" ]
          default: "3.13.2"
          toggle: true
      Redis:
        versions:
          available: [ "6.2.14", "7.2.4", "7.4.0" ]
          default: "7.2.4"
          toggle: true
      Singlestore:
        versions:
          available: ["8.1.32", "8.5.30", "8.7.9"]
          default: "8.7.9"
          toggle: true
      Solr:
        versions:
          available: [ "8.11.2", "9.4.1", "9.6.1" ]
          default: "9.6.1"
          toggle: true
      ZooKeeper:
        versions:
          available: [ "3.7.2", "3.8.3", "3.9.1" ]
          default: "3.8.3"
          toggle: true
    storageClasses:
      available: []
      default: ""
      toggle: true
    tls:
      default: false
      toggle: true
    clusterIssuers:
      available: []
      default: ""
      toggle: true
    expose:
      default: false
      toggle: true
    showPreview: false
    monitoring:
      # Name of monitoring agent (one of "prometheus.io", "prometheus.io/operator", "prometheus.io/builtin")
      agent: prometheus.io/operator
      exporter:
        resources: # +doc-gen:break
          requests:
            cpu: 100m
            memory: 128Mi
      toggle: true
    alerts:
      toggle: true
    archiver:
      toggle: true
      default: false
