apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubedb-ui-presets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kubedb-ui-presets
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubedb-ui-presets
  targetNamespace: kubedb
  storageNamespace: kubedb
  chart:
    spec:
      chart: kubedb-ui-presets
      version: "v2024.6.18"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
