apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prepare-cluster
  namespace: kubeops
  labels:
    app.kubernetes.io/component: prepare-cluster
spec:
  interval: 5m
  timeout: 30m
  releaseName: prepare-cluster
  targetNamespace: kubedb
  storageNamespace: kubedb
  chart:
    spec:
      chart: prepare-cluster
      version: "v2023.12.21"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
