apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-opscenter
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: grafana-opscenter
  targetNamespace: monitoring
  chart:
    spec:
      chart: grafana-opscenter
      version: "v2023.03.23"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    grafana-operator:
      enabled: true
    grafana-ui-server:
      enabled: true
    kube-grafana-dashboards:
      enabled: true
