apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: grafana-operator
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: grafana-operator
      version: "v0.0.2"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
