apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: kubeops
  labels:
    app.kubernetes.io/component: gatekeeper
spec:
  interval: 5m
  timeout: 30m
  releaseName: gatekeeper
  targetNamespace: gatekeeper-system
  storageNamespace: gatekeeper-system
  chart:
    spec:
      chart: gatekeeper
      version: "3.13.3"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  values:
    constraintViolationsLimit: 100
    # disableMutation: true
    # disableValidatingWebhook: true
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
