apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kyverno
spec:
  interval: 5m
  timeout: 30m
  releaseName: kyverno
  targetNamespace: kyverno
  storageNamespace: kyverno
  chart:
    spec:
      chart: kyverno
      version: "3.8.4"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
