apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: config-syncer
  namespace: kubeops
  labels:
    app.kubernetes.io/component: config-syncer
spec:
  interval: 5m
  timeout: 30m
  releaseName: config-syncer
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: config-syncer
      version: "0.14.6"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    mode: enterprise
