apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: sealed-secrets
spec:
  interval: 5m
  timeout: 30m
  releaseName: sealed-secrets
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: sealed-secrets
      version: "1.0.50"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
