apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
kind: Kustomization
patchesJson6902:
- path: patch.yaml
  target:
    group: kubedb.com
    kind: Redis
    name: redis
    namespace: demo
    version: v1alpha2
resources:
- redis-backupblueprint.yaml
