apiVersion: v1
kind: Secret
metadata:
  name: oracle-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: oracle-config
  namespace: demo
stringData:
  oracle.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: oracle-ca
  namespace: demo
spec:
  ca:
    secretName: oracle-ca
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: oracle
    app.kubernetes.io/name: oracles.kubedb.com
    release: prometheus-stack
  name: oracle
  namespace: demo
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: oracle
      app.kubernetes.io/name: oracles.kubedb.com
---
apiVersion: kubedb.com/v1alpha2
kind: Oracle
metadata:
  name: oracle
  namespace: oracle
spec:
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: oracle
        component: oracle-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: oracle
        - effect: NoSchedule
          key: component
          operator: Equal
          value: oracle-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: oracle
          resources:
            requests:
              cpu: 700m
              memory: "1200Mi"
  version: 3.8.3
  replicas: 3
  storage:
    resources:
      requests:
        storage: "100Mi"
    #    storageClassName: standard
    accessModes:
      - ReadWriteOnce
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  deletionPolicy: Halt
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: OracleAutoscaler
metadata:
  name: oracle
  namespace: demo
spec:
  databaseRef:
    name: oracle
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    oracle:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
---
apiVersion: catalog.appscode.com/v1alpha1
kind: OracleBinding
metadata:
  name: oracle
  namespace: demo
spec:
  sourceRef:
    name: oracle
    namespace: demo
