apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: ContributorInsights
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/contributorinsights
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    region: us-east-2
    tableNameSelector:
      matchLabels:
        testing.upbound.io/example-name: mytable

---

apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/table
  labels:
    testing.upbound.io/example-name: mytable
  name: mytable
spec:
  forProvider:
    attribute:
    - name: exampleHashKey
      type: S
    hashKey: exampleHashKey
    region: us-east-2
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
    billingMode: PAY_PER_REQUEST

---
