apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: GlobalTable
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/globaltable
  labels:
    testing.upbound.io/example-name: myTable
  name: mytable
spec:
  forProvider:
    region: us-east-2
    replica:
      - regionName: us-east-2

---

apiVersion: dynamodb.aws.kubeform.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1alpha1/table
  labels:
    testing.upbound.io/example-name: mytable
  name: mytable
spec:
  forProvider:
    attribute:
    - name: exampleHashKey
      type: S
    hashKey: exampleHashKey
    region: us-east-2
    streamEnabled: true
    streamViewType: NEW_AND_OLD_IMAGES
    billingMode: PAY_PER_REQUEST

---


