apiVersion: v1
kind: Secret
metadata:
  name: qdrant-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: qdrant-config
  namespace: demo
stringData:
  qdrant.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: qdrant-ca
  namespace: demo
spec:
  ca:
    secretName: qdrant-ca
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: qdrant
    app.kubernetes.io/name: qdrants.kubedb.com
    release: prometheus-stack
  name: qdrant
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: qdrant
      app.kubernetes.io/name: qdrants.kubedb.com
---
apiVersion: kubedb.com/v1alpha2
kind: Qdrant
metadata:
  name: qdrant
  namespace: default
spec:
  version: "24.4.1"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  podTemplate:
    spec:
      containers:
        - name: qdrant
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
      podPlacementPolicy:
        name: default
      nodeSelector:
        app: qdrants.kubedb.com
        instance: hello
        namespace: default
        nodepool: standard-bsv2-family
      tolerations:
        - key: app
          operator: "Equal"
          value: "qdrants.kubedb.com"
          effect: "NoSchedule"
        - key: instance
          operator: "Equal"
          value: hello
          effect: "NoSchedule"
        - key: namespace
          operator: "Equal"
          value: default
          effect: "NoSchedule"
        - key: nodepool
          operator: "Equal"
          value: standard-bsv2-family
          effect: "NoSchedule"
  deletionPolicy: WipeOut
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: QdrantAutoscaler
metadata:
  name: qdrant
  namespace: demo
spec:
  databaseRef:
    name: qdrant
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    qdrant:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
