apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aceshifter
  namespace: kubeops
  labels:
    app.kubernetes.io/component: aceshifter
spec:
  interval: 5m
  timeout: 30m
  releaseName: aceshifter
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: aceshifter
      version: "v2024.10.24"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
