apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ui-server
  namespace: kubeops
spec:
  interval: 5m
  timeout: 10m
  releaseName: kube-ui-server
  targetNamespace: kubeops
  chart:
    spec:
      chart: kube-ui-server
      version: "v2023.03.23"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
