apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: demo
spec:
  kernelSettings:
    privileged: true
    sysctls:
    - name: vm.max_map_count
      value: "262144"
  version: xpack-7.13.2
  storageType: Durable
  replicas: 3
  storage:
    storageClassName: "linode-block-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi