apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubestash
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kubestash
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubestash
  targetNamespace: stash
  storageNamespace: stash
  chart:
    spec:
      chart: kubestash
      version: "v2023.10.30-rc.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    features:
      enterprise: true
