apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: stash
  targetNamespace: stash
  storageNamespace: stash
  chart:
    spec:
      chart: stash
      version: "v2023.02.28"
      sourceRef:
        kind: HelmRepository
        name: stashed
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    features:
      enterprise: true
