apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash-presets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: stash-presets
spec:
  interval: 5m
  timeout: 30m
  releaseName: stash-presets
  targetNamespace: stash
  storageNamespace: stash
  chart:
    spec:
      chart: stash-presets
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    clusterMetadata:
      name: arnob-new-ui-local
      uid: 39554065-3968-4589-adac-d41a880d4c99
    kubestash:
      backend:
        provider: s3
        s3:
          auth:
            AWS_ACCESS_KEY_ID: 34F9JI2JM8DOJC6NUPII
            AWS_SECRET_ACCESS_KEY: ""
          spec:
            bucket: arnob
            endpoint: us-east-1.linodeobjects.com
            prefix: new-ui-local
            region: us-east-1
        azure:
          spec:
            container: ""
            # prefix: ""
            # maxConnections: 0
          auth:
            AZURE_ACCOUNT_NAME: ""
            AZURE_ACCOUNT_KEY: ""
        gcs:
          spec:
            bucket: ""
            # prefix: ""
            # maxConnections: 0
          auth:
            GOOGLE_PROJECT_ID: ""
            GOOGLE_SERVICE_ACCOUNT_JSON_KEY: ""
      encryptionSecret: abcde
      retentionPolicy: keep-1wk
      schedule: '*/30 * * * *'
      storageSecret:
        create: true
    usePrefix: ""
    tool: KubeStash
