apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3
  namespace: demo
spec:
  storage:
    provider: s3
    s3:
      endpoint: s3.amazonaws.com
      bucket: kubestash-demo
      region: us-west-1
      prefix: /kubestash-backup
      secretName: s3-storage-cred
  usagePolicy:
    allowedNamespaces:
      from: All
  default: true
  deletionPolicy: WipeOut
