apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: sample-mongo
  namespace: demo
spec:
  version: "4.2.3"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  init:
    script:
      secret:
        secretName: mongo-init-script
  terminationPolicy: WipeOut
