apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: kubeops
  labels:
    app.kubernetes.io/component: keda
spec:
  interval: 5m
  timeout: 30m
  releaseName: keda
  targetNamespace: keda
  storageNamespace: keda
  chart:
    spec:
      chart: keda
      version: "2.12.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
