apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-config
  namespace: demo
stringData:
  clickhouse.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: clickhouse-ca
  namespace: demo
spec:
  ca:
    secretName: clickhouse-ca
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/name: clickhouses.kubedb.com
    release: prometheus-stack
  name: clickhouse
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/name: clickhouses.kubedb.com
---
apiVersion: kubedb.com/v1alpha2
kind: ClickHouse
metadata:
  name: clickhouse
  namespace: default
spec:
  version: "24.4.1"
  clusterTopology:
    clickHouseKeeper:
      node:
        host: clickhouse-keeper.click-keeper
        port: 2181
    cluster:
      name: click1
      shards: 2
      replicas: 3
      storageType: Durable
      storage:
        storageClassName: default
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      podTemplate:
        spec:
          containers:
            - name: clickhouse
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
          podPlacementPolicy:
            name: default
          nodeSelector:
            app: clickhouses.kubedb.com
            instance: hello
            namespace: default
            nodepool: standard-bsv2-family
          tolerations:
            - key: app
              operator: "Equal"
              value: "clickhouses.kubedb.com"
              effect: "NoSchedule"
            - key: instance
              operator: "Equal"
              value: hello
              effect: "NoSchedule"
            - key: namespace
              operator: "Equal"
              value: default
              effect: "NoSchedule"
            - key: nodepool
              operator: "Equal"
              value: standard-bsv2-family
              effect: "NoSchedule"
  deletionPolicy: WipeOut
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
---
apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: clickhouse
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: ClickHouse
    name: clickhouse
    namespace: demo
  backends:
    - name: clickhouse-backend
      storageRef:
        name: clickhouse-storage
        namespace: demo
      retentionPolicy:
        name: clickhouse-retention-policy
        namespace: demo
  sessions:
    - name: clickhouse-frequent-backup
      scheduler:
        failedJobsHistoryLimit: 4
        jobTemplate:
          backoffLimit: 2
          template:
            spec:
              containerSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                runAsGroup: 0
                runAsNonRoot: true
                runAsUser: 999
                seccompProfile:
                  type: RuntimeDefault
              nodeSelector:
                kubernetes.io/os: linux
        schedule: 0 */2 * * *
        successfulJobsHistoryLimit: 2
      sessionHistoryLimit: 3
      repositories:
        - name: clickhouse-repo
          backend: clickhouse-backend
          directory: /clickhouse-repo
          encryptionSecret:
            name: clickhouse-encryption-secret
            namespace: demo
      addon:
        name: clickhouse-addon
        tasks:
          - name: logical-backup
        jobTemplate:
          spec:
            containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsGroup: 0
              runAsNonRoot: true
              runAsUser: 999
              seccompProfile:
                type: RuntimeDefault
            nodeSelector:
              kubernetes.io/os: linux
---
apiVersion: core.kubestash.com/v1alpha1
kind: BackupBlueprint
metadata:
  name: clickhouse
  namespace: demo
spec:
  usagePolicy:
    allowedNamespaces:
      from: Same
  backupConfigurationTemplate:
    backends:
      - name: clickhouse-backend
        storageRef:
          name: clickhouse-storage
          namespace: demo
        retentionPolicy:
          name: clickhouse-retention-policy
          namespace: demo
    sessions:
      - name: clickhouse-frequent-backup
        scheduler:
          failedJobsHistoryLimit: 4
          jobTemplate:
            backoffLimit: 2
            template:
              spec:
                containerSecurityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsGroup: 0
                  runAsNonRoot: true
                  runAsUser: 999
                  seccompProfile:
                    type: RuntimeDefault
                nodeSelector:
                  kubernetes.io/os: linux
          schedule: 0 */2 * * *
          successfulJobsHistoryLimit: 2
        sessionHistoryLimit: 3
        repositories:
          - name: clickhouse-repo
            backend: clickhouse-backend
            directory: /clickhouse-repo
            encryptionSecret:
              name: clickhouse-encryption-secret
              namespace: demo
        addon:
          name: clickhouse-addon
          tasks:
            - name: logical-backup
          jobTemplate:
            spec:
              containerSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                runAsGroup: 0
                runAsNonRoot: true
                runAsUser: 999
                seccompProfile:
                  type: RuntimeDefault
              nodeSelector:
                kubernetes.io/os: linux
---
apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: clickhouse
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: ClickHouse
    name: clickhouse
    namespace: demo
  dataSource:
    snapshot: latest
    repository: clickhouse-repo
    encryptionSecret:
      name: clickhouse-encryption-secret
      namespace: demo
  addon:
    name: clickhouse-addon
    tasks:
      - name: logical-backup-restore
    jobTemplate:
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        securityContext:
          runAsUser: 999
          runAsGroup: 0
    containerRuntimeSettings:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: ClickHouseAutoscaler
metadata:
  name: clickhouse
  namespace: demo
spec:
  databaseRef:
    name: clickhouse
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    clickhouse:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
---
apiVersion: catalog.appscode.com/v1alpha1
kind: ClickHouseBinding
metadata:
  name: clickhouse
  namespace: demo
spec:
  sourceRef:
    name: clickhouse
    namespace: demo
