apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-swift-auth-token
  namespace: demo
stringData:
  auth_token: <auth-token>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-swift-creds
  namespace: demo
stringData:
  password: <password>
  username: <username>
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    swift:
      authTokenSecret: vault-backend-swift-auth-token
      credentialSecret: vault-backend-swift-creds
  replicas: 1
  unsealer:
    mode:
      kubernetesSecret:
        secretName: vault-keys
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
