apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql
  namespace: demo
  labels:
    release: prometheus-stack
    app.kubernetes.io/name: mysqls.kubedb.com
    app.kubernetes.io/instance: mysql
spec:
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/name: mysqls.kubedb.com
      app.kubernetes.io/instance: mysql
  endpoints:
  - port: metrics
    honorLabels: true
    interval: 30s
    path: /metrics
