apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
kind: Kustomization
patchesJson6902:
- path: patch.yaml
  target:
    group: kubedb.com
    kind: RedisSentinel
    name: redissentinel
    namespace: demo
    version: v1alpha2
resources:
- redis.yaml
