apiVersion: kubedb.com/v1alpha2
kind: RedisSentinel
metadata:
  name: redissentinel
  namespace: demo
spec:
  version: "6.2.5"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
