apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: service-gateway
  namespace: kubeops
  labels:
    app.kubernetes.io/component: service-gateway
spec:
  interval: 5m
  timeout: 30m
  releaseName: service-gateway
  targetNamespace: ace
  storageNamespace: ace
  chart:
    spec:
      chart: voyager-gateway
      version: "v0.0.0-latest"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
