apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: service-backend
  namespace: kubeops
  labels:
    app.kubernetes.io/component: service-backend
spec:
  interval: 5m
  timeout: 30m
  releaseName: service-backend
  targetNamespace: ace
  storageNamespace: ace
  chart:
    spec:
      chart: service-backend
      version: "v2024.2.11"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
