apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-creds
  namespace: demo
stringData:
  access_key: <access_key>
  secret_key: <secret_key>
  session_token: <session-token>
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    dynamodb:
      credentialSecret: vault-backend-creds
      sessionTokenSecret: vault-backend-creds
  replicas: 1
  unsealer:
    mode:
      kubernetesSecret:
        secretName: vault-keys
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
