apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver-cacerts
  namespace: kubeops
  labels:
    app.kubernetes.io/component: cert-manager-csi-driver-cacerts
spec:
  interval: 5m
  timeout: 30m
  releaseName: cert-manager-csi-driver-cacerts
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager-csi-driver-cacerts
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
