apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco-ui-server
  namespace: kubeops
  labels:
    app.kubernetes.io/component: falco-ui-server
spec:
  interval: 5m
  timeout: 30m
  releaseName: falco-ui-server
  targetNamespace: falco
  storageNamespace: falco
  chart:
    spec:
      chart: falco-ui-server
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
