apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: kubeops
  labels:
    app.kubernetes.io/component: falco
spec:
  interval: 5m
  timeout: 30m
  releaseName: falco
  targetNamespace: falco
  storageNamespace: falco
  chart:
    spec:
      chart: falco
      version: "3.8.4"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    driver:
      kind: modern-bpf
    falco:
      grpc:
        enabled: true
      grpc_output:
        enabled: true
      http_output:
        enabled: true
        insecure: true
        url: http://falco-ui-server:8080/falcoevents
      json_include_output_property: true
      json_output: true
      modern_bpf:
        cpus_for_each_syscall_buffer: 1
    falcosidekick:
      enabled: false
      webui:
        enabled: false
    tty: true
