apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper-templates
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: gatekeeper-templates
  targetNamespace: gatekeeper-system
  storageNamespace: gatekeeper-system
  chart:
    spec:
      name: gatekeeper-library
      version: "v2023.03.23"
      sourceRef:
        kind: HelmRepository
        name: kubeops
        namespace: kubeops
  values:
    enable: templates
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
