apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper-templates
  namespace: kubeops
  labels:
    app.kubernetes.io/component: gatekeeper-templates
spec:
  interval: 5m
  timeout: 30m
  releaseName: gatekeeper-templates
  targetNamespace: gatekeeper-system
  storageNamespace: gatekeeper-system
  chart:
    spec:
      chart: gatekeeper-library
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  values:
    enable: templates
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
