apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevault-opscenter
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubevault-opscenter
  targetNamespace: kubevault
  storageNamespace: kubevault
  chart:
    spec:
      chart: kubevault-opscenter
      version: "v2023.03.03"
      sourceRef:
        kind: HelmRepository
        name: kubevault
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
