apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scanner
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: scanner
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: scanner
      version: "v2023.03.23"
      sourceRef:
        kind: HelmRepository
        name: kubeops
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
