apiVersion: storage.kubestash.com/v1alpha1
kind: Repository
metadata:
  name: ace-repo
  namespace: demo
spec:
  appRef:
    apiGroup: kubedb.com
    kind: Postgres
    name: ace-db
    namespace: ace
  deletionPolicy: Delete
  encryptionSecret:
    name: default-encryption-secret
    namespace: stash
  path: ace/ace-db
  storageRef:
    name: default
    namespace: stash
