apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-std
  namespace: demo
spec:
  version: "4.2.3"
  sslMode: requireSSL
  tls:
    issuerRef:
      name: mongo-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  terminationPolicy: WipeOut
