apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-config
  namespace: demo
stringData:
  md-config.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pgbouncer-ca
  namespace: demo
spec:
  ca:
    secretName: pgbouncer-ca
---
apiVersion: kubedb.com/v1
kind: PgBouncer
metadata:
  name: pgbouncer
  namespace: demo
spec:
  authSecret:
    name: pgbouncer-auth
  configSecret:
    name: pgbouncer-config
  monitor:
    agent: prometheus.io
    prometheus:
      serviceMonitor:
        interval: 30s
        labels:
          release: prometheus-stack
  podTemplate:
    spec:
      args:
      - --character-set-server=utf8mb4
      env:
      - name: MYSQL_DATABASE
        value: mdDB
      resources:
        requests:
          cpu: 250m
          memory: 1Gi

  version: "1.17.0"
  replicas: 3
  database:
    syncUsers: true
    databaseName: "postgres"
    databaseRef:
      name: "postgres"
      namespace: demo
  connectionPool:
    port: 5432
    defaultPoolSize: 20
    poolMode: session
    minPoolSize: 0
    maxClientConnections: 20
    reservePoolSize: 5
    maxDBConnections: 0
    maxUserConnections: 0
    statsPeriodSeconds: 60
    authType: md5
    adminUsers:
    - rakib
    authUser: rakib
  tls:
    certificates:
    - alias: server
      dnsNames:
      - localhost
      ipAddresses:
      - 127.0.0.1
      subject:
        organizations:
        - kubedb:server
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: pgbouncer-ca
  deletionPolicy: WipeOut
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: pgbouncer
    app.kubernetes.io/name: pgbouncers.kubedb.com
    release: prometheus-stack
  name: pgbouncer
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: pgbouncer
      app.kubernetes.io/name: pgbouncers.kubedb.com
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: PgBouncerAutoscaler
metadata:
  name: pgbouncer
  namespace: demo
spec:
  databaseRef:
    name: repl
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    pgbouncer:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
---
apiVersion: catalog.appscode.com/v1alpha1
kind: PgBouncerBinding
metadata:
  name: pgbouncer
  namespace: demo
spec:
  sourceRef:
    name: pgbouncer
    namespace: demo
