apiVersion: rds.aws.upbound.io/v1beta1
kind: ClusterParameterGroup
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/parametergroup
  labels:
    testing.upbound.io/example-name: example
  name: example-parametergroup
spec:
  forProvider:
    region: us-east-2
    family: postgres13
    description: example
    parameter:
      - name: application_name
        value: "example"
        applyMethod: immediate