apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
  labels:
    testing.upbound.io/example-name: example-dbinstance
  name: example-dbinstance-1
spec:
  forProvider:
    dbSubnetGroupName: example-subnetgroup
    region: us-east-2
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    instanceClass: db.t3.micro
    name: example
    engine: postgres
    engineVersion: "13.7"
    username: adminuser
    autoGeneratePassword: true
    passwordSecretRef:
      key: password
      name: example-dbinstance
      namespace: upbound-system
    backupWindow: "09:46-10:16"
    maintenanceWindow: "Mon:00:00-Mon:03:00"
    publiclyAccessible: false
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    kmsKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-key
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: default

---

apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
  labels:
    testing.upbound.io/example-name: sample-key
  name: sample-key-1
spec:
  forProvider:
    region: us-east-2
    description: Created with Crossplane
    deletionWindowInDays: 7

---
apiVersion: v1
kind: Secret
metadata:
  name: example-dbinstance
  namespace: upbound-system
type: Opaque
data:
  password: MTIzNDU2Nzg=
  #12345678


---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: sample-db-vpc
spec:
  forProvider:
    region: us-east-2
    cidrBlock: 172.16.0.0/16
    tags:
      Name: DemoVpc

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: sample-db-subnet1
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2b
    vpcIdRef:
      name: sample-db-vpc
    cidrBlock: 172.16.10.0/24

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: sample-db-subnet2
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2c
    vpcIdRef:
      name: sample-db-vpc
    cidrBlock: 172.16.20.0/24

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: sample-db-subnet3
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2a
    vpcIdRef:
      name: sample-db-vpc
    cidrBlock: 172.16.30.0/24

---

apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: example-subnetgroup
spec:
  forProvider:
    region: us-east-2
    subnetIdRefs:
      - name: sample-db-subnet1
      - name: sample-db-subnet2
      - name: sample-db-subnet3
    tags:
      Name: My DB subnet group