apiVersion: kubedb.com/v1alpha2
kind: RedisSentinel
metadata:
  name: redissentinel
  namespace: demo
spec:
  version: "6.2.5"
  replicas: 3
  storageType: Durable
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      name: redis-ca
      kind: Issuer
  storage:
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
