apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capa-vpc-peering-operator
  namespace: kubeops
  labels:
    app.kubernetes.io/component: capa-vpc-peering-operator
spec:
  interval: 5m
  timeout: 30m
  releaseName: capa-vpc-peering-operator
  targetNamespace: crossplane-system
  storageNamespace: crossplane-system
  chart:
    spec:
      chart: capa-vpc-peering-operator
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
