apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: cluster-autoscaler
  targetNamespace: capi-cluster
  storageNamespace: capi-cluster
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.29.0"
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    cloudProvider: clusterapi
    autoscalingGroups:
      - name: default
        minSize: 1
        maxSize: 6
    extraArgs:
      logtostderr: null
      stderrthreshold: null
      v: null
