apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: crossplane
  targetNamespace: crossplane-system
  storageNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane
      version: "1.12.2"
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
