apiVersion: v1
kind: Secret
metadata:
  name: redissentinel-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: redissentinel-config
  namespace: demo
stringData:
  redis.conf: |
    databases 10
    maxclients 500
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-ca
  namespace: demo
spec:
  ca:
    secretName: redis-ca
---
apiVersion: kubedb.com/v1alpha2
kind: RedisSentinel
metadata:
  name: redissentinel
  namespace: demo
spec:
  authSecret:
    name: redissentinel-auth
  configSecret:
    name: redissentinel-config
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceMonitor:
        interval: 30s
        labels:
          release: prometheus-stack
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  terminationPolicy: WipeOut
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: redis-ca
  version: 6.2.5
