apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: aws-secret-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
    namespace: demo
  aws:
    credentialSecret: aws-cred
    region: <region>
    leaseConfig:
      lease: 1h
      leaseMax: 1h
