apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mongodb
  namespace: demo
spec:
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: WipeOut
  version: 4.2.3
