apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: kubeops
  labels:
    app.kubernetes.io/component: grafana-operator
spec:
  interval: 5m
  timeout: 30m
  releaseName: grafana-operator
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: grafana-operator
      version: "v0.0.3"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
