apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: inbox-server
  namespace: kubeops
  labels:
    app.kubernetes.io/component: inbox-server
spec:
  interval: 5m
  timeout: 30m
  releaseName: inbox-server
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: inbox-server
      version: "v2024.5.3"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
