apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: kubeops
  labels:
    app.kubernetes.io/component: opentelemetry-kube-stack
spec:
  interval: 5m
  timeout: 30m
  releaseName: opentelemetry-kube-stack
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: opentelemetry-kube-stack
      version: "0.107.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
