apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: panopticon
  namespace: kubeops
  labels:
    app.kubernetes.io/component: panopticon
spec:
  interval: 5m
  timeout: 30m
  releaseName: panopticon
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: panopticon
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
