apiVersion: v1
kind: Secret
metadata:
  name: db2-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: kubedb.com/v1alpha2
kind: DB2
metadata:
  name: db2
  namespace: default
spec:
  version: "24.4.1"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  podTemplate:
    spec:
      containers:
        - name: db2
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
      podPlacementPolicy:
        name: default
      nodeSelector:
        app: db2s.kubedb.com
        instance: hello
        namespace: default
        nodepool: standard-bsv2-family
      tolerations:
        - key: app
          operator: "Equal"
          value: "db2s.kubedb.com"
          effect: "NoSchedule"
        - key: instance
          operator: "Equal"
          value: hello
          effect: "NoSchedule"
        - key: namespace
          operator: "Equal"
          value: default
          effect: "NoSchedule"
        - key: nodepool
          operator: "Equal"
          value: standard-bsv2-family
          effect: "NoSchedule"
  deletionPolicy: WipeOut
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: DB2Autoscaler
metadata:
  name: db2
  namespace: default
spec:
  databaseRef:
    name: db2
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    db2:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
