apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubevault
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kubevault
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubevault
  targetNamespace: kubevault
  storageNamespace: kubevault
  chart:
    spec:
      chart: kubevault
      version: "v2023.10.26-rc.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
