- op: add
  path: /metadata/annotations
  value:
    stash.appscode.com/backup-blueprint: mysql-backupblueprint
    stash.appscode.com/schedule: '*/7 * * * *'
- op: add
  path: /spec/replicas
  value: 1
