apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver-provider-virtual-secrets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: secrets-store-csi-driver-provider-virtual-secrets
spec:
  interval: 5m
  timeout: 30m
  releaseName: secrets-store-csi-driver-provider-virtual-secrets
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: secrets-store-csi-driver-provider-virtual-secrets
      version: "v2025.3.14"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
