apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: virtual-secrets-server
  namespace: kubeops
  labels:
    app.kubernetes.io/component: virtual-secrets-server
spec:
  interval: 5m
  timeout: 30m
  releaseName: virtual-secrets-server
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: virtual-secrets-server
      version: "v2025.3.14"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
