apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-consul-creds
  namespace: demo
stringData:
  aclToken: <acl-token>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-consul-tls
  namespace: demo
stringData:
  ca.crt: <ca-cert>
  client.crt: <client-cert>
  client.key: <client-key>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unsealer-aws-creds
  namespace: demo
stringData:
  access_key: <access_key>
  secret_key: <secret_key>
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    consul:
      aclTokenSecretName: vault-backend-consul-creds
      address: http://consul-server.default.svc:8500
      path: vault
      tlsSecretName: vault-backend-consul-tls
  replicas: 1
  unsealer:
    mode:
      awsKmsSsm:
        credentialSecret: vault-unsealer-aws-creds
        kmsKeyID: <kms-key-id>
        region: <region>
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
