apiVersion: v1
kind: Secret
metadata:
  name: ferret-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ferret-config
  namespace: demo
stringData:
  mongod.conf: |
    max_connections = 200
type: Opaque
---
apiVersion: kubedb.com/v1alpha2
kind: FerretDB
metadata:
  name: ferret
  namespace: demo
spec:
  version: "1.18.0"
  authSecret:
    externallyManaged: false
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: ferretdb
        component: ferretdb-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: ferretdb
        - effect: NoSchedule
          key: component
          operator: Equal
          value: ferretdb-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: ferretdb
          resources:
            requests:
              "cpu": 400m
              "memory": "1200Mi"
  sslMode: disabled
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
  deletionPolicy: WipeOut
  monitor:
    agent: prometheus.io/builtin
#    prometheus:
#      serviceMonitor:
#        labels:
#          release: prometheus
#        interval: 10s
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ferret-ca
  namespace: sample
spec:
  ca:
    secretName: ferretdb-ca
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: ferretdb
    app.kubernetes.io/name: ferretdbs.kubedb.com
    release: prometheus-stack
  name: ferret
  namespace: demo
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: ferretdb
      app.kubernetes.io/name: ferretdbs.kubedb.com
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: FerretDBAutoscaler
metadata:
  name: ferret
  namespace: demo
spec:
  databaseRef:
    name: ferret
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    primary:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
---
apiVersion: catalog.appscode.com/v1alpha1
kind: FerretDBBinding
metadata:
  name: ferret
  namespace: demo
spec:
  sourceRef:
    name: ferret
    namespace: demo
