apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-creds
  namespace: demo
stringData:
  auth_token: <auth-token>
  password: <password>
  username: <username>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unsealer-creds
  namespace: demo
stringData:
  client-cert: <client-cert>
  client-cert-password: <client-cert-password>
  client-id: <client-cert>
  client-secret: <client-secret>
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    swift:
      authTokenSecret: vault-backend-creds
      credentialSecret: vault-backend-creds
  replicas: 1
  unsealer:
    mode:
      azureKeyVault:
        aadClientSecret: vault-unsealer-creds
        clientCertSecret: vault-unsealer-creds
        vaultBaseURL: <vault-base-url>
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
