apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ace-mc-addons
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: ace-mc-addons
  targetNamespace: open-cluster-management-addon
  storageNamespace: open-cluster-management-addon
  chart:
    spec:
      chart: ace-ocm-addons
      version: "v2024.2.13"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
