apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fluxcd-manager-mc
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: fluxcd-manager-mc
  targetNamespace: open-cluster-management-addon
  storageNamespace: open-cluster-management-addon
  chart:
    spec:
      chart: fluxcd-manager
      version: "v2024.2.25"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  dependsOn:
    - name: cluster-manager-hub
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    kubeconfigSecretName: multicluster-controlplane-svc-kubeconfig
