apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-mc
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: ingress-nginx-mc
  targetNamespace: multicluster-controlplane
  storageNamespace: multicluster-controlplane
  chart:
    spec:
      chart: ingress-nginx
      version: "v2024.2.13"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
