apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multicluster-controlplane
  namespace: kubeops
  labels:
    ace.appscode.com/feature: multicluster-controlplane
spec:
  interval: 5m
  timeout: 30m
  releaseName: multicluster-controlplane
  targetNamespace: multicluster-controlplane
  storageNamespace: multicluster-controlplane
  chart:
    spec:
      chart: multicluster-controlplane
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    apiserver:
      generateCA: true
    enableSelfManagement: true
    autoApprovalBootstrapUsers: "system:admin"
    features: DefaultClusterSet=true,ManagedClusterAutoApproval=true,ManifestWorkReplicaSet=true
    image: ghcr.io/kluster-manager/multicluster-controlplane:latest
    imagePullPolicy: Always
    loadbalancer:
      enabled: true
    pvc:
      storageClassName: ""
    route:
      enabled: false
    securityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsUser: 10001
