apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kubeops
  labels:
    app.kubernetes.io/component: csi-driver-nfs
spec:
  interval: 5m
  timeout: 30m
  releaseName: csi-driver-nfs
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
