apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: kubeops
  labels:
    app.kubernetes.io/component: longhorn
spec:
  interval: 5m
  timeout: 30m
  releaseName: longhorn
  targetNamespace: longhorn-system
  storageNamespace: longhorn-system
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
