apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kubeops
  labels:
    app.kubernetes.io/component: snapshot-controller
spec:
  interval: 5m
  timeout: 30m
  releaseName: snapshot-controller
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: snapshot-controller
      version: "2.0.3"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
