apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  replicas: 1
  version: 1.8.2
  backend:
    raft:
      path: "/vault/data"
      storage:
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
  unsealer:
    secretShares: 5
    secretThreshold: 3
    mode:
      azureKeyVault:
        vaultBaseURL: <vault-base-url>
        clientCertSecret: vault-unsealer-creds
        aadClientSecret: vault-unsealer-creds
