apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLFirewallRule
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlfirewallrule
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    endIpAddress: 10.0.17.62
    serverIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssqlelasticpoolsrv
    startIpAddress: 10.0.17.62

---

# apiVersion: azure.kubedb.com/v1alpha1
# kind: ResourceGroup
# metadata:
#   annotations:
#     meta.kubedb.com/example-id: sql/v1alpha1/mssqlelasticpool
#   labels:
#     testing.kubedb.com/example-name: mssqlelasticpool-rg
#   name: mssqlelasticpool-rg
# spec:
#   forProvider:
#     location: West Europe

# ---

# apiVersion: sql.azure.kubedb.com/v1alpha1
# kind: MSSQLServer
# metadata:
#   annotations:  
#     uptest.kubedb.com/timeout: "3600"
#     meta.kubedb.com/example-id: sql/v1alpha1/mssqlelasticpool
#   labels:
#     testing.kubedb.com/example-name: mssqlelasticpoolsrv
#   name: mssqlelasticpoolsrv
# spec:
#   forProvider:
#     administratorLogin: 4dm1n157r470r
#     administratorLoginPasswordSecretRef:
#       key: example-key
#       name: example-secret
#       namespace: upbound-system
#     location: West Europe
#     resourceGroupNameSelector:
#       matchLabels:
#         testing.kubedb.com/example-name: mssqlelasticpool-rg
#     version: "12.0"

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: example-secret
#   namespace: upbound-system
# type: Opaque
# data:
#   example-key: dGVzdFBhc3N3b3JkITEyMw==