apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLVirtualNetworkRule
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlvirtualnetworkrule
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-vn-rule
    subnetIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlvirtualnetworkrule
  labels:
    testing.kubedb.com/example-name: example-vn-rule
  name: example-vn-rule
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: password
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-sql-vn-rule
    version: "12.0"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlvirtualnetworkrule
  labels:
    testing.kubedb.com/example-name: example-sql-vn-rule
  name: example-sql-vn-rule
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlvirtualnetworkrule
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.7.29.0/29
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-sql-vn-rule
    serviceEndpoints:
    - Microsoft.Sql
    virtualNetworkNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlvirtualnetworkrule
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.7.29.0/29
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-sql-vn-rule

---

apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123