#  error
# InvalidStorageAccountCredentials" Message="The provided storage account shared access signature or account storage key is not valid

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerVulnerabilityAssessment
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Requires existing blob storage path and key"
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    recurringScans:
    - emailSubscriptionAdmins: true
      emails:
      - email@example1.com
      - email@example2.com
      enabled: true
    serverSecurityAlertPolicyIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    storageAccountAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-storage-account2
      namespace: upbound-system
    storageContainerPath: https://crossplestoraccsql13722.blob.core.windows.net/example-storage-account

---
apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
    upjet.kubedb.com/manual-intervention: "Requires existing blob storage path and key"
  labels:
    testing.kubedb.com/example-name: mssqlvulnassessmentacc
  name: mssqlvulnassessmentacc
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssql-rg
  writeConnectionSecretToRef:
    name: example-storage-account2
    namespace: upbound-system

---

apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Container
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Requires existing blob storage path and key"
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
  labels:
    testing.kubedb.com/example-name: mssqlvulnassessmentcont
  name: mssqlvulnassessmentcont
spec:
  forProvider:
    containerAccessType: private
    storageAccountNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssqlvulnassessmentacc

---
apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerSecurityAlertPolicy
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlserversecurityalertpolicy
  labels:
    testing.kubedb.com/example-name: example
  name: alertpolicyname
spec:
  forProvider:
    disabledAlerts:
    - Sql_Injection
    - Data_Exfiltration
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssql-rg
    retentionDays: 0
    serverNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-srv
    state: Enabled

# ---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:  
    uptest.kubedb.com/timeout: "3600"
    meta.kubedb.com/example-id: sql/v1alpha1/example-srv
  labels:
    testing.kubedb.com/example-name: example-srv
  name: example-srv
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssql-rg
    version: "12.0"

---


apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlelasticpool
  labels:
    testing.kubedb.com/example-name: mssql-rg
  name: mssql-rg
spec:
  forProvider:
    location: West Europe

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
data:
  example-key: dGVzdFBhc3N3b3JkITEyMw==

---


apiVersion: v1
kind: Secret
metadata:
  name: example-secret-stor
  namespace: upbound-system
type: Opaque
data:
  example-key: SmNQL1krSlFtOWhaVnNIQzQ4TlVTR0lSUmRnU0I1WU1mRlVBcU1SbHZPdGdQaVFUMUdEUVNoZ2hCRWFhYXk0OVlIbUl5S1ltZ2pMYytBU3R3RlR2SXc9PQ==

---