apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLElasticPool
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlelasticpool
  labels:
    testing.kubedb.com/example-name: examplemssqlelasticpool
  name: examplemssqlelasticpool
spec:
  forProvider:
    location: West Europe
    maxSizeGb: 5
    perDatabaseSettings:
    - maxCapacity: 4
      minCapacity: 1
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssqlelasticpool-rg
    serverNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssqlelasticpoolsrv
    sku:
    - capacity: 4
      name: GP_Gen5
      tier: GeneralPurpose
      family: Gen5

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlelasticpool
  labels:
    testing.kubedb.com/example-name: mssqlelasticpool-rg
  name: mssqlelasticpool-rg
spec:
  forProvider:
    location: West Europe

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:  
    uptest.kubedb.com/timeout: "3600"
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlelasticpool
  labels:
    testing.kubedb.com/example-name: mssqlelasticpoolsrv
  name: mssqlelasticpoolsrv
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssqlelasticpool-rg
    version: "12.0"

---

apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
data:
  example-key: dGVzdFBhc3N3b3JkITEyMw==