apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLJobCredential
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqljobcredential
  labels:
    testing.kubedb.com/example-name: examplemssqljobcred
  name: examplemssqljobcred
spec:
  forProvider:
    jobAgentIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: examplemssqljobagent
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    username: my-username

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLJobAgent
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqljobagent
  labels:
    testing.kubedb.com/example-name: examplemssqljobagent
  name: examplemssqljobagent
spec:
  forProvider:
    databaseIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-db
    location: West Europe
    name: example-job-agent

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqldatabaseextendedauditingpolicy
  labels:
    testing.kubedb.com/example-name: example-db
  name: database
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-srv

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:  
    uptest.kubedb.com/timeout: "3600"
    meta.kubedb.com/example-id: sql/v1alpha1/example-srv
  labels:
    testing.kubedb.com/example-name: example-srv
  name: example-srv
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssql-rg
    version: "12.0"

---
apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlelasticpool
  labels:
    testing.kubedb.com/example-name: mssql-rg
  name: mssql-rg
spec:
  forProvider:
    location: West Europe

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
data:
  example-key: dGVzdFBhc3N3b3JkITEyMw==