apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqldatabaseextendedauditingpolicy
  labels:
    testing.kubedb.com/example-name: example
  name: database
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqldatabaseextendedauditingpolicy
  labels:
    testing.kubedb.com/example-name: example
  name: mssqlservername
spec:
  forProvider:
    administratorLogin: missadministrator
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    version: "12.0"

---

apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
data:
  example-key: dGVzdFBhc3N3b3JkITEyMw==

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqldatabaseextendedauditingpolicy
  labels:
    testing.kubedb.com/example-name: example
  name: policy-rg
spec:
  forProvider:
    location: West Europe