apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-sql
spec:
  package: xpkg.kubedb.com/upbound/provider-azure-sql:v0.38.2

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-storage
spec:
  package: xpkg.kubedb.com/upbound/provider-azure-storage:v0.38.2

---