apiVersion: sql.gcp.kubedb.com/v1alpha1
kind: User
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/user
  labels:
    testing.kubedb.com/example-name: example_user
  name: example-user
spec:
  forProvider:
    passwordSecretRef:
      name: example-sql-user
      namespace: upbound-system
      key: password
    instanceSelector:
      matchLabels:
        testing.kubedb.com/example-name: example_instance

---

apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/user
  labels:
    testing.kubedb.com/example-name: example_user
  name: example-sql-user
  namespace: upbound-system

---

# apiVersion: sql.gcp.kubedb.com/v1alpha1
# kind: DatabaseInstance
# metadata:
#   annotations:
#     meta.kubedb.com/example-id: sql/v1alpha1/databaseinstance
#   labels:
#     testing.kubedb.com/example-name: example_instance
#   # ${Rand...} is not valid YAML and is used with automated testing
#   name: example-instance
# spec:
#   forProvider:
#     region: "us-central1"
#     databaseVersion: "MYSQL_5_7"
#     settings:
#       - tier: "db-f1-micro"
#         diskSize: 20
#     deletionProtection: false # allow crossplane to delete the instance automatically
#   writeConnectionSecretToRef:
#     name: example-sql-db-instance-secret
#     namespace: upbound-system