apiVersion: sql.gcp.kubedb.com/v1alpha1
kind: Database
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/database
  labels:
    testing.kubedb.com/example-name: example_database
  # ${Rand...} is not valid YAML and is used with automated testing
  name: example-database
spec:
  forProvider:
    instanceSelector:
      matchLabels:
        testing.kubedb.com/example-name: example_instance