# error :-
# connect failed: cannot get a terraform workspace for resource: cannot get id: project: no such field


apiVersion: sql.gcp.kubedb.com/v1alpha1
kind: SSLCert
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Depends on SQL instance to be successfully deleted"
    meta.kubedb.com/example-id: sql/v1alpha1/sslcert
  labels:
    testing.kubedb.com/example-name: example_cert
  name: example-cert
spec:
  forProvider:
    commonName: client-name
    instanceSelector:
      matchLabels:
        testing.kubedb.com/example-name: example_instance
  writeConnectionSecretToRef:
    name: example-sql-ssl-secret
    namespace: upbound-system

---
# apiVersion: sql.gcp.kubedb.com/v1alpha1
# kind: DatabaseInstance
# metadata:
#   annotations:
#     meta.kubedb.com/example-id: sql/v1alpha1/databaseinstance
#   labels:
#     testing.kubedb.com/example-name: example_instance
#   # ${Rand...} is not valid YAML and is used with automated testing
#   name: example-instance
# spec:
#   forProvider:
#     region: "us-central1"
#     databaseVersion: "MYSQL_5_7"
#     settings:
#       - tier: "db-f1-micro"
#         diskSize: 20
#     deletionProtection: false # allow crossplane to delete the instance automatically
#   writeConnectionSecretToRef:
#     name: example-sql-db-instance-secret
#     namespace: upbound-system