apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: single-zone-dedicated
  namespace: kubedb-managed
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
spec:
  clusterName: tapo-test
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: tapo-test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: single-zone-dedicated
      version: v1.27.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: single-zone-dedicated
  namespace: kubedb-managed
spec:
  mode: User
  name: dsinglezone
  sku: Standard_D2s_v3
  availabilityZones:
    - "1"
  scaling:
    maxSize: 5
    minSize: 3
  taints:
    - effect: NoSchedule
      key: dedicated
      value: "true"
---
apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-cluster-dedicated-single-zone
  namespace: demo
spec:
  disableAuth: true
  version: 7.2.0
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: "100Mi"
    storageClassName: "managed-premium"
    accessModes:
      - ReadWriteOnce
  podTemplate:
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: dsinglezone
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
      tolerations:
        - key: dedicated
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  terminationPolicy: WipeOut
