apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis-cluster-shared-single-zone
  namespace: demo
spec:
  disableAuth: true
  version: 7.2.0
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: "100Mi"
    storageClassName: "managed-premium"
    accessModes:
      - ReadWriteOnce
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
  terminationPolicy: WipeOut
