apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
kind: Kustomization
patchesJson6902:
- path: patch.yaml
  target:
    group: kubevault.com
    kind: VaultServer
    name: vault
    namespace: demo
    version: v1alpha1
resources:
- vault-unsealer-creds.yaml
