apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator-shard-manager
  namespace: kubeops
  labels:
    app.kubernetes.io/component: operator-shard-manager
spec:
  interval: 5m
  timeout: 30m
  releaseName: operator-shard-manager
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: operator-shard-manager
      version: "v2025.1.17"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
