apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sidekick
  namespace: kubeops
  labels:
    app.kubernetes.io/component: sidekick
spec:
  interval: 5m
  timeout: 30m
  releaseName: sidekick
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: sidekick
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
