apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-ops-manager
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: capi-ops-manager
  targetNamespace: capi-cluster
  storageNamespace: capi-cluster
  chart:
    spec:
      chart: capi-ops-manager
      version: "v2024.2.13"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
