apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-presets
  namespace: kubeops
  labels:
    app.kubernetes.io/component: cluster-presets
spec:
  interval: 5m
  timeout: 30m
  releaseName: cluster-presets
  targetNamespace: capi-cluster
  storageNamespace: capi-cluster
  chart:
    spec:
      chart: cluster-presets
      version: "v2024.6.3"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
