apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-machine-operator
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: docker-machine-operator
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: docker-machine-operator
      version: "0.16.4"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
