apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres
  namespace: demo
  annotations:
    stash.appscode.com/backup-blueprint: postgres-backupblueprint
    stash.appscode.com/schedule: "*/7 * * * *"
spec:
  version: "13.2"
  replicas: 1
  standbyMode: Hot
  storageType: Durable
  storage:
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
