apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  replicas: 1
  version: 1.8.2
  backend:
    consul:
      address: "http://consul-server.default.svc:8500"
      path: "vault"
      aclTokenSecretName: vault-backend-creds
      tlsSecretName: vault-backend-tls
  unsealer:
    secretShares: 5
    secretThreshold: 3
    mode:
      kubernetesSecret:
        secretName: vault-keys