apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-api
  namespace: kubeops
  labels:
    app.kubernetes.io/component: gateway-api
spec:
  interval: 5m
  timeout: 30m
  releaseName: gateway-api
  targetNamespace: envoy-gateway-system
  storageNamespace: envoy-gateway-system
  chart:
    spec:
      chart: gateway-api
      version: v1.0.0
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
