apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mongodb
  namespace: demo
spec:
  replicaSet:
    name: replicaset
  replicas: 3
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  deletionPolicy: WipeOut
  version: 4.2.3
