apiVersion: v1
kind: Secret
metadata:
  name: vault-backend-creds
  namespace: demo
stringData:
  account_key: <account_key>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-unsealer-creds
  namespace: demo
stringData:
  sa.json: |-
    {
      "key": "value",
    }
type: Opaque
---
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  backend:
    azure:
      accountKeySecret: vault-backend-creds
      accountName: <account-name>
  replicas: 1
  unsealer:
    mode:
      googleKmsGcs:
        bucket: <bucket-name>
        credentialSecret: vault-unsealer-creds
        kmsCryptoKey: <kms-key>
        kmsKeyRing: <kms-ring>
        kmsLocation: <kms-location>
        kmsProject: <project-name>
    secretShares: 5
    secretThreshold: 3
  version: 1.8.2
