apiVersion: v1
kind: Secret
metadata:
  name: ignite-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ignite-config
  namespace: demo
stringData:
  ignite.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ignite-ca
  namespace: demo
spec:
  ca:
    secretName: ignite-ca
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: ignite
    app.kubernetes.io/name: ignites.kubedb.com
    release: prometheus-stack
  name: ignite
  namespace: demo
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: ignite
      app.kubernetes.io/name: ignites.kubedb.com
---
apiVersion: kubedb.com/v1alpha2
kind: Ignite
metadata:
  name: ignite
  namespace: ignite
spec:
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: ignite
        component: ignite-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: ignite
        - effect: NoSchedule
          key: component
          operator: Equal
          value: ignite-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: ignite
          resources:
            requests:
              cpu: 700m
              memory: "1200Mi"
  version: 3.8.3
  replicas: 3
  storage:
    resources:
      requests:
        storage: "100Mi"
#    storageClassName: standard
    accessModes:
      - ReadWriteOnce
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  deletionPolicy: Halt
---
apiVersion: autoscaling.kubedb.com/v1alpha1
kind: IgniteAutoscaler
metadata:
  name: ignite
  namespace: demo
spec:
  databaseRef:
    name: ignite
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    ignite:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
    nodeTopology:
      name: standard-basv2-family
