apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleServerConfiguration
metadata:
  name: interactive-timeout
  annotations:
    upjet.kubedb.com/manual-intervention: "The resource depends on a Server and it needs a manual intervention."
    # external-name should be a valid MySQL configuration name.
    # See https://dev.mysql.com/doc/refman/5.7/en/server-configuration.html
    crossplane.io/external-name: interactive_timeout
spec:
  forProvider:
    resourceGroupNameRef:
      name: example-rg-dbformysql
    serverNameRef:
      name: example-upbound
    value: "600"
---
# faced this error
# observe failed: cannot run plan: plan failed: Instance cannot be destroyed: Resource azurerm_mysql_flexible_server_configuration.
# interactive-timeout has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed.
#  To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.