apiVersion: v1
kind: Secret
metadata:
  name: hazelcast-auth
  namespace: demo
stringData:
  password: thisIs1StrongPassword
  username: root
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: hazelcast-config
  namespace: demo
stringData:
  hazelcast.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hazelcast-ca
  namespace: demo
spec:
  ca:
    secretName: hazelcast-ca
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/name: hazelcasts.kubedb.com
    release: prometheus-stack
  name: hazelcast
  namespace: demo
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: hazelcast
      app.kubernetes.io/name: hazelcasts.kubedb.com
---
apiVersion: kubedb.com/v1alpha2
kind: Hazelcast
metadata:
  name: hazelcast
  namespace: hazelcast
spec:
  podTemplate:
    spec:
      nodeSelector:
        app: kubedb
        instance: hazelcast
        component: hazelcast-database
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: kubedb
        - effect: NoSchedule
          key: instance
          operator: Equal
          value: hazelcast
        - effect: NoSchedule
          key: component
          operator: Equal
          value: hazelcast-database
        - effect: NoSchedule
          key: nodepool_type
          operator: Equal
          value: n2-standard-2
      containers:
        - name: hazelcast
          resources:
            requests:
              cpu: 700m
              memory: "1200Mi"
  version: 3.8.3
  replicas: 3
  storage:
    resources:
      requests:
        storage: "100Mi"
    #    storageClassName: standard
    accessModes:
      - ReadWriteOnce
  serviceTemplates:
    - alias: primary
      spec:
        type: LoadBalancer
  deletionPolicy: Halt
---
apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: hazelcast
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Hazelcast
    name: hazelcast
    namespace: demo
  backends:
    - name: hazelcast-backend
      storageRef:
        name: hazelcast-storage
        namespace: demo
      retentionPolicy:
        name: hazelcast-retention-policy
        namespace: demo
  sessions:
    - name: hazelcast-frequent-backup
      scheduler:
        failedJobsHistoryLimit: 4
        jobTemplate:
          backoffLimit: 2
          template:
            spec:
              containerSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsGroup: 0
                runAsNonRoot: true
                runAsUser: 999
                seccompProfile:
                  type: RuntimeDefault
              nodeSelector:
                kubernetes.io/os: linux
        schedule: 0 */2 * * *
        successfulJobsHistoryLimit: 2
      sessionHistoryLimit: 3
      repositories:
        - name: hazelcast-repo
          backend: hazelcast-backend
          directory: /mongo-repo
          encryptionSecret:
            name: hazelcast-encryption-secret
            namespace: demo
      addon:
        name: hazelcast-addon
        tasks:
          - name: logical-backup
        jobTemplate:
          spec:
            containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              runAsGroup: 0
              runAsNonRoot: true
              runAsUser: 999
              seccompProfile:
                type: RuntimeDefault
            nodeSelector:
              kubernetes.io/os: linux
---
apiVersion: core.kubestash.com/v1alpha1
kind: BackupBlueprint
metadata:
  name: hazelcast
  namespace: demo
spec:
  usagePolicy:
    allowedNamespaces:
      from: Same
  backupConfigurationTemplate:
    backends:
      - name: hazelcast-backend
        storageRef:
          name: hazelcast-storage
          namespace: demo
        retentionPolicy:
          name: hazelcast-retention-policy
          namespace: demo
    sessions:
      - name: hazelcast-frequent-backup
        scheduler:
          failedJobsHistoryLimit: 4
          jobTemplate:
            backoffLimit: 2
            template:
              spec:
                containerSecurityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  runAsGroup: 0
                  runAsNonRoot: true
                  runAsUser: 999
                  seccompProfile:
                    type: RuntimeDefault
                nodeSelector:
                  kubernetes.io/os: linux
          schedule: 0 */2 * * *
          successfulJobsHistoryLimit: 2
        sessionHistoryLimit: 3
        repositories:
          - name: hazelcast-repo
            backend: hazelcast-backend
            directory: /mongo-repo
            encryptionSecret:
              name: hazelcast-encryption-secret
              namespace: demo
        addon:
          name: hazelcast-addon
          tasks:
            - name: logical-backup
          jobTemplate:
            spec:
              containerSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsGroup: 0
                runAsNonRoot: true
                runAsUser: 999
                seccompProfile:
                  type: RuntimeDefault
              nodeSelector:
                kubernetes.io/os: linux
---
apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: hazelcast
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Hazelcast
    name: hazelcast
    namespace: demo
  dataSource:
    snapshot: latest
    repository: hazelcast-repo
    encryptionSecret:
      name: hazelcast-encryption-secret
      namespace: demo
  addon:
    name: hazelcast-addon
    tasks:
      - name: logical-backup-restore
    jobTemplate:
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        securityContext:
          runAsUser: 999
          runAsGroup: 0
    containerRuntimeSettings:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
