apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kubeops
  labels:
    app.kubernetes.io/component: aws-load-balancer-controller
spec:
  interval: 5m
  timeout: 30m
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
