apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-credential-manager
  namespace: kubeops
  labels:
    app.kubernetes.io/component: aws-credential-manager
spec:
  interval: 5m
  timeout: 30m
  releaseName: aws-credential-manager
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: aws-credential-manager
      version: "v2025.3.14"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
