apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kubeops
  labels:
    app.kubernetes.io/component: aws-ebs-csi-driver
spec:
  interval: 5m
  timeout: 30m
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: "2.23.0"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
