apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mysql
  namespace: demo
  labels:
    app.kubernetes.io/name: mysqls.kubedb.com
    app.kubernetes.io/instance: mysql
spec:
  schedule: "*/5 * * * *"
  repository:
    name: mysql-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mysql
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
