apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: retentionpolicy-14-weeks
  namespace: demo
spec:
  successfulSnapshots: # Hourly, daily for 7 days
    hourly: 8
    daily: 7
    weekly: 14
  failedSnapshots:
    last: 2
  usagePolicy:
    allowedNamespaces:
      from: All