apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../modes/sharded
kind: Kustomization
resources:
- mongodb-config-secret.yaml
- mongodb-configserver-config-secret.yaml
- mongodb-mongos-config-secret.yaml
- mongodb-shard-config-secret.yaml
- mongodb.yaml
